stages:
  - buildVerify
variables:
  LC_ALL: "en_US.UTF-8"
  LANG: "en_US.UTF-8"
  GITLAB_FLUTTER_VERSION: $GITLAB_FLUTTER_VERSION
  GITLAB_IOS_VERSION: $GITLAB_IOS_VERSION
  GITLAB_ANDROID_VERSION: $GITLAB_ANDROID_VERSION


buildVerify:
  stage: buildVerify
  script:
    # 编译
    - echo $gitlab_uploadToGit
    - sh bundle.sh $GITLAB_FLUTTER_VERSION $GITLAB_IOS_VERSION $GITLAB_ANDROID_VERSION
  tags:
    - mac-studio
  only:
    - web
    - api
    - pipelines
  



