name: mop
description: A Finogeeks MiniProgram Flutter SDK.
version: '2.33.9'
homepage: https://github.com/finogeeks/mop-flutter-sdk

environment:
  sdk: '>=2.1.0 <3.0.0'
  flutter: '^1.10.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.finogeeks.mop
        pluginClass: MopPlugin
      ios:
        pluginClass: MopPlugin
